// Code generated by Copilot. DO NOT EDIT.
// This file is auto-generated from Widget.json. Update this file if new scenarios are added to the JSON.
package widget_test

import (
	"testing"
)

// AccountUnbinding
func TestAccountUnbindSuccess(t *testing.T) {
	// ...skeleton...
}
func TestAccountUnbindFailAccessTokenNotExist(t *testing.T) {
	// ...skeleton...
}
func TestAccountUnbindFailInvalidUserStatus(t *testing.T) {
	// ...skeleton...
}
func TestAccountUnbindFailInvalidParams(t *testing.T) {
	// ...skeleton...
}
