// Code generated by Copilot. DO NOT EDIT.
// This file is auto-generated from Widget.json. Update this file if new scenarios are added to the JSON.
package widget_test

import (
	"testing"
)

// ApplyToken
func TestApplyTokenSuccess(t *testing.T) {
	// ...skeleton...
}
func TestApplyTokenFailExpiredAuthcode(t *testing.T) {
	// ...skeleton...
}
func TestApplyTokenFailAuthcodeUsed(t *testing.T) {
	// ...skeleton...
}
func TestApplyTokenFailAuthcodeInvalid(t *testing.T) {
	// ...skeleton...
}
func TestApplyTokenFailInvalidParams(t *testing.T) {
	// ...skeleton...
}
func TestApplyTokenFailInvalidMandatoryFields(t *testing.T) {
	// ...skeleton...
}
func TestApplyTokenFailInvalidSignature(t *testing.T) {
	// ...skeleton...
}
