// Code generated by Copilot. DO NOT EDIT.
// This file is auto-generated from Widget.json. Update this file if new scenarios are added to the JSON.
package widget_test

import (
	"context"
	"encoding/json"
	"testing"

	"uat-script/helper"

	widget "github.com/dana-id/dana-go/widget/v1"
	"github.com/google/uuid"
)

const (
	widgetPaymentTitleCase = "Payment"
	widgetPaymentJsonPath  = "../../../resource/request/components/Widget.json"
)

// Payment
func TestPaymentSuccess(t *testing.T) {
	caseName := "PaymentSuccess"
	jsonDict, err := helper.GetRequest(widgetPaymentJsonPath, widgetPaymentTitleCase, caseName)
	if err != nil {
		t.Fatalf("Failed to get request data: %v", err)
	}
	partnerReferenceNo := uuid.New().String()
	jsonDict["partnerReferenceNo"] = partnerReferenceNo

	request := &widget.WidgetPaymentRequest{}
	jsonBytes, err := json.Marshal(jsonDict)
	if err != nil {
		t.Fatalf("Failed to marshal JSON: %v", err)
	}
	err = json.Unmarshal(jsonBytes, &request)
	if err != nil {
		t.Fatalf("Failed to unmarshal JSON: %v", err)
	}
	ctx := context.Background()
	apiResponse, httpResponse, err := helper.ApiClient.WidgetAPI.WidgetPayment(ctx).WidgetPaymentRequest(*request).Execute()
	if err != nil {
		t.Fatalf("API request failed: %v", err)
	}
	defer httpResponse.Body.Close()
	responseJSON, err := apiResponse.MarshalJSON()
	if err != nil {
		t.Fatalf("Failed to convert response to JSON: %v", err)
	}

	// Create variable dictionary for dynamic values
	variableDict := map[string]interface{}{
		"partnerReferenceNo": partnerReferenceNo,
	}

	err = helper.AssertResponse(widgetPaymentJsonPath, widgetPaymentTitleCase, caseName, string(responseJSON), variableDict)
	if err != nil {
		t.Fatal(err)
	}
}

func TestPaymentFailInvalidFormat(t *testing.T) {
	t.Skip("Skip for now")
	caseName := "PaymentFailInvalidFormat"
	jsonDict, err := helper.GetRequest(widgetPaymentJsonPath, widgetPaymentTitleCase, caseName)
	if err != nil {
		t.Fatalf("Failed to get request data: %v", err)
	}
	partnerReferenceNo := uuid.New().String()
	jsonDict["partnerReferenceNo"] = partnerReferenceNo

	request := &widget.WidgetPaymentRequest{}
	jsonBytes, err := json.Marshal(jsonDict)
	if err != nil {
		t.Fatalf("Failed to marshal JSON: %v", err)
	}
	err = json.Unmarshal(jsonBytes, &request)
	if err != nil {
		t.Fatalf("Failed to unmarshal JSON: %v", err)
	}
	ctx := context.Background()
	apiResponse, httpResponse, err := helper.ApiClient.WidgetAPI.WidgetPayment(ctx).WidgetPaymentRequest(*request).Execute()
	if err != nil {
		t.Fatalf("Expected error for case %s but API call succeeded", caseName)
	}
	defer httpResponse.Body.Close()
	responseJSON, err := apiResponse.MarshalJSON()
	if err != nil {
		t.Fatalf("Failed to convert response to JSON: %v", err)
	}
	variableDict := map[string]interface{}{
		"partnerReferenceNo": partnerReferenceNo,
	}
	err = helper.AssertFailResponse(widgetPaymentJsonPath, widgetPaymentTitleCase, caseName, string(responseJSON), variableDict)
	if err != nil {
		t.Fatal(err)
	}
}

func TestPaymentFailMissingOrInvalidMandatoryField(t *testing.T) {
	t.Skip("Skip for now")
	caseName := "PaymentFailMissingOrInvalidMandatoryField"
	jsonDict, err := helper.GetRequest(widgetPaymentJsonPath, widgetPaymentTitleCase, caseName)
	if err != nil {
		t.Fatalf("Failed to get request data: %v", err)
	}
	partnerReferenceNo := uuid.New().String()
	jsonDict["partnerReferenceNo"] = partnerReferenceNo

	request := &widget.WidgetPaymentRequest{}
	jsonBytes, err := json.Marshal(jsonDict)
	if err != nil {
		t.Fatalf("Failed to marshal JSON: %v", err)
	}
	err = json.Unmarshal(jsonBytes, &request)
	if err != nil {
		t.Fatalf("Failed to unmarshal JSON: %v", err)
	}
	ctx := context.Background()
	apiResponse, httpResponse, err := helper.ApiClient.WidgetAPI.WidgetPayment(ctx).WidgetPaymentRequest(*request).Execute()
	if err != nil {
		t.Fatalf("Expected error for case %s but API call succeeded", caseName)
	}
	defer httpResponse.Body.Close()
	responseJSON, err := apiResponse.MarshalJSON()
	if err != nil {
		t.Fatalf("Failed to convert response to JSON: %v", err)
	}
	variableDict := map[string]interface{}{
		"partnerReferenceNo": partnerReferenceNo,
	}
	err = helper.AssertFailResponse(widgetPaymentJsonPath, widgetPaymentTitleCase, caseName, string(responseJSON), variableDict)
	if err != nil {
		t.Fatal(err)
	}
}

func TestPaymentFailInvalidSignature(t *testing.T) {
	t.Skip("Skip for now")
	caseName := "PaymentFailInvalidSignature"
	jsonDict, err := helper.GetRequest(widgetPaymentJsonPath, widgetPaymentTitleCase, caseName)
	if err != nil {
		t.Fatalf("Failed to get request data: %v", err)
	}
	partnerReferenceNo := uuid.New().String()
	jsonDict["partnerReferenceNo"] = partnerReferenceNo

	request := &widget.WidgetPaymentRequest{}
	jsonBytes, err := json.Marshal(jsonDict)
	if err != nil {
		t.Fatalf("Failed to marshal JSON: %v", err)
	}
	err = json.Unmarshal(jsonBytes, &request)
	if err != nil {
		t.Fatalf("Failed to unmarshal JSON: %v", err)
	}
	ctx := context.Background()
	endpoint := "https://api.sandbox.dana.id/rest/redirection/v1.0/debit/payment-host-to-host"
	resourcePath := "/rest/redirection/v1.0/debit/payment-host-to-host"
	customHeaders := map[string]string{"X-SIGNATURE": "invalid_signature"}
	variableDict := map[string]interface{}{
		"partnerReferenceNo": partnerReferenceNo,
	}
	err = helper.ExecuteAndAssertErrorResponse(
		t,
		ctx,
		request,
		"POST",
		endpoint,
		resourcePath,
		widgetPaymentJsonPath,
		widgetPaymentTitleCase,
		caseName,
		customHeaders,
		variableDict,
	)
	if err != nil {
		t.Fatal(err)
	}
}

func TestPaymentFailGeneralError(t *testing.T) {
	t.Skip("Skip for now")
	caseName := "PaymentFailGeneralError"
	jsonDict, err := helper.GetRequest(widgetPaymentJsonPath, widgetPaymentTitleCase, caseName)
	if err != nil {
		t.Fatalf("Failed to get request data: %v", err)
	}
	partnerReferenceNo := uuid.New().String()
	jsonDict["partnerReferenceNo"] = partnerReferenceNo

	request := &widget.WidgetPaymentRequest{}
	jsonBytes, err := json.Marshal(jsonDict)
	if err != nil {
		t.Fatalf("Failed to marshal JSON: %v", err)
	}
	err = json.Unmarshal(jsonBytes, &request)
	if err != nil {
		t.Fatalf("Failed to unmarshal JSON: %v", err)
	}
	ctx := context.Background()
	apiResponse, httpResponse, err := helper.ApiClient.WidgetAPI.WidgetPayment(ctx).WidgetPaymentRequest(*request).Execute()
	if err != nil {
		t.Fatalf("Expected error for case %s but API call succeeded", caseName)
	}
	defer httpResponse.Body.Close()
	responseJSON, err := apiResponse.MarshalJSON()
	if err != nil {
		t.Fatalf("Failed to convert response to JSON: %v", err)
	}
	variableDict := map[string]interface{}{
		"partnerReferenceNo": partnerReferenceNo,
	}
	err = helper.AssertFailResponse(widgetPaymentJsonPath, widgetPaymentTitleCase, caseName, string(responseJSON), variableDict)
	if err != nil {
		t.Fatal(err)
	}
}

func TestPaymentFailTransactionNotPermitted(t *testing.T) {
	t.Skip("Skip for now")
	caseName := "PaymentFailTransactionNotPermitted"
	jsonDict, err := helper.GetRequest(widgetPaymentJsonPath, widgetPaymentTitleCase, caseName)
	if err != nil {
		t.Fatalf("Failed to get request data: %v", err)
	}
	partnerReferenceNo := uuid.New().String()
	jsonDict["partnerReferenceNo"] = partnerReferenceNo

	request := &widget.WidgetPaymentRequest{}
	jsonBytes, err := json.Marshal(jsonDict)
	if err != nil {
		t.Fatalf("Failed to marshal JSON: %v", err)
	}
	err = json.Unmarshal(jsonBytes, &request)
	if err != nil {
		t.Fatalf("Failed to unmarshal JSON: %v", err)
	}
	ctx := context.Background()
	apiResponse, httpResponse, err := helper.ApiClient.WidgetAPI.WidgetPayment(ctx).WidgetPaymentRequest(*request).Execute()
	if err != nil {
		t.Fatalf("Expected error for case %s but API call succeeded", caseName)
	}
	defer httpResponse.Body.Close()
	responseJSON, err := apiResponse.MarshalJSON()
	if err != nil {
		t.Fatalf("Failed to convert response to JSON: %v", err)
	}
	variableDict := map[string]interface{}{
		"partnerReferenceNo": partnerReferenceNo,
	}
	err = helper.AssertFailResponse(widgetPaymentJsonPath, widgetPaymentTitleCase, caseName, string(responseJSON), variableDict)
	if err != nil {
		t.Fatal(err)
	}
}
