// Code generated by Copilot. DO NOT EDIT.
// This file is auto-generated from Widget.json. Update this file if new scenarios are added to the JSON.
package widget_test

import (
	"testing"
)

// QueryOrder
func TestQueryOrderSuccessPaid(t *testing.T) {
	// ...skeleton...
}
func TestQueryOrderSuccessInitiated(t *testing.T) {
	// ...skeleton...
}
func TestQueryOrderSuccessPaying(t *testing.T) {
	// ...skeleton...
}
func TestQueryOrderSuccessCancelled(t *testing.T) {
	// ...skeleton...
}
func TestQueryOrderNotFound(t *testing.T) {
	// ...skeleton...
}
func TestQueryOrderFailInvalidField(t *testing.T) {
	// ...skeleton...
}
func TestQueryOrderFailInvalidMandatoryField(t *testing.T) {
	// ...skeleton...
}
func TestQueryOrderFailUnauthorized(t *testing.T) {
	// ...skeleton...
}
func TestQueryOrderFailTransactionNotFound(t *testing.T) {
	// ...skeleton...
}
func TestQueryOrderFailGeneralError(t *testing.T) {
	// ...skeleton...
}
