// Code generated by Copilot. DO NOT EDIT.
// This file is auto-generated from Widget.json. Update this file if new scenarios are added to the JSON.
package widget_test

import (
	"testing"
)

// RefundOrder
func TestRefundOrderValidScenario(t *testing.T) {
	// ...skeleton...
}
func TestRefundInProcess(t *testing.T) {
	// ...skeleton...
}
func TestRefundFailExceedPaymentAmount(t *testing.T) {
	// ...skeleton...
}
func TestRefundFailNotAllowedByAgreement(t *testing.T) {
	// ...skeleton...
}
func TestRefundFailExceedRefundWindowTime(t *testing.T) {
	// ...skeleton...
}
func TestRefundFailMultipleRefundNotAllowed(t *testing.T) {
	// ...skeleton...
}
func TestRefundFailDuplicateRequest(t *testing.T) {
	// ...skeleton...
}
func TestRefundFailOrderNotPaid(t *testing.T) {
	// ...skeleton...
}
func TestRefundFailParameterIllegal(t *testing.T) {
	// ...skeleton...
}
func TestRefundFailMandatoryParameterInvalid(t *testing.T) {
	// ...skeleton...
}
func TestRefundFailOrderNotExist(t *testing.T) {
	// ...skeleton...
}
func TestRefundFailInsufficientMerchantBalance(t *testing.T) {
	// ...skeleton...
}
func TestRefundFailInvalidSignature(t *testing.T) {
	// ...skeleton...
}
func TestRefundFailTimeout(t *testing.T) {
	// ...skeleton...
}
func TestRefundFailIdempotent(t *testing.T) {
	// ...skeleton...
}
func TestRefundFailMerchantStatusAbnormal(t *testing.T) {
	// ...skeleton...
}
