// Code generated by Copilot. DO NOT EDIT.
// This file is auto-generated from Widget.json. Update this file if new scenarios are added to the JSON.
package widget_test

import (
	"testing"
)

// TransactionList
func TestTransactionListSuccess(t *testing.T) {
	// ...skeleton...
}
func TestTransactionListFailInvalidParam(t *testing.T) {
	// ...skeleton...
}
func TestTransactionListFailDataNotAvailable(t *testing.T) {
	// ...skeleton...
}
func TestTransactionListFailSystemError(t *testing.T) {
	// ...skeleton...
}
func TestTransactionListFailInvalidSignature(t *testing.T) {
	// ...skeleton...
}
func TestTransactionListFailInvalidToken(t *testing.T) {
	// ...skeleton...
}
func TestTransactionListFailInvalidMandatoryParameter(t *testing.T) {
	// ...skeleton...
}
